apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wprb-rocks-ingress
  namespace: wprb-rocks
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  rules:
  - host: api.wprb.rocks
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wprb-rocks-backend-service
            port:
              number: 3000
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: wprb-rocks-websockets-service
            port:
              number: 8080
  tls:
  - hosts:
    - api.wprb.rocks
    secretName: wprb-rocks-io-cert
