apiVersion: v1
kind: Pod
metadata:
  name: wprb-rocks-pod
  namespace: wprb-rocks
spec:
  restartPolicy: Never
  containers:
  - name: wprb-rocks-pod
    image: gammons1/wprb-rocks:v15
    env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: database-url
          key: database-url
    - name: SPOTIFY_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: spotify-oauth
          key: spotify-app-id
    - name: SPOTIFY_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: spotify-oauth
          key: spotify-app-secret
    - name: RAILS_ENV
      value: "production"
    - name: RAILS_LOG_TO_STDOUT
      value: "true"
    - name: SECRET_KEY_BASE
      valueFrom:
        secretKeyRef:
          name: rails-secret
          key: rails-secret
    command:
      - "/bin/bash"
      - "-c"
      - "sleep 10000"

