---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wprb-rocks-sqlite-pvc-nfs
  namespace: wprb-rocks
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
