source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.7'

gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 1.7'
gem 'puma', '~> 6.0'
gem 'bootsnap', require: false
gem 'openssl', '~> 3.2.2'

gem 'fuzzy_match'
gem 'graphql'
gem 'http'
gem 'nokogiri'
gem 'rack-cors'
gem 'spotify-search', git: 'https://github.com/gammons/spotify-search.git', branch: 'main'

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'graphiql-rails'
  gem 'rspec-rails', '~> 6.0'
end

group :development do
  gem 'listen', '~> 3.8'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
